#!/bin/sh
# For RedHat and cousins:
# chkconfig: - 99 01
# description: Encrypted/authenticated DNS proxy
# processname: DNSCrypt-Proxy

### BEGIN INIT INFO
# Provides:          /config/dns/dns
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: DNSCrypt client proxy
# Description:       Encrypted/authenticated DNS proxy
### END INIT INFO
PhienBan="20200322c"
TM="/config/dns"
CauHinh="$TM/CauHinh.toml"
cmd="$TM/dns "-config" "$CauHinh""

echo "# Đang chạy Dịch Vụ $PhienBan"

name=$(basename $(readlink -f $0))
pid_file="/var/run/$name.pid"
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

[ -e /etc/sysconfig/$name ] && . /etc/sysconfig/$name

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps $(get_pid) > /dev/null 2>&1
}

case "$1" in
    start)
        if is_running; then
            echo "DNSCrypt đang chạy"
        else
            echo "Đang gọi $name..."
            cd "$TM"
            $cmd >> "$stdout_log" 2>> "$stderr_log" &
            echo $! > "$pid_file"
            if ! is_running; then
                echo "Không thể chạy DNSCrypt, xem lỗi: cat $stdout_log | cat $stderr_log"
                exit 1
            fi
        fi
    ;;
    stop)
        if is_running; then
            echo -n "Đang dừng $name..."
            kill $(get_pid)
            for i in $(seq 1 10)
            do
                if ! is_running; then
                    break
                fi
                echo -n "."
                sleep 1
            done
            echo
            if is_running; then
                echo "DNSCrypt không dừng được, có lẽ DNSCrypt đã tắt hoặc việc dừng DNSCrypt thất bại"
                exit 1
            else
                echo "Đã dừng DNSCrypt"
                if [ -f "$pid_file" ]; then
                    rm "$pid_file"
                fi
            fi
        else
            echo "DNSCrypt không chạy"
        fi
    ;;
    restart)
        $0 stop
        if is_running; then
            echo "Không thể dừng DNSCrypt, dừng việc gọi DNSCrypt lại"
            exit 1
        fi
        $0 start
    ;;
    status)
        if is_running; then
            echo "DNSCrypt đang chạy"
        else
            echo "DNSCrypt không chạy"
            exit 1
        fi
    ;;
    *)
    echo "# Tham số: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac
exit 0