#!/bin/bash
PhienBan="20200321a"
OS=`uname -m`; x64="x86_64"; arm="armv7l"; Android="aarch64"
if [ $OS == $x64 ]; then if [ -d /www/cgi-bin ]; then sp="/usr/sbin/sp"; echo "OS: $OS | OpenWRT"; 
else sp="/sbin/sp"; echo "OS: $OS"; fi; if [ ! -f "$sp" ]; then 
	echo "Đang tải SpeedTest"; curl -sLo $sp https://bom.to/sp64; chmod +x $sp; fi; fi

if [ $OS == $arm ]; then if [ -d /www/cgi-bin ]; then sp="/usr/sbin/sp"; echo "OS: $OS | OpenWRT"; 
else sp="/opt/sbin/sp"; echo "OS: $OS"; fi; if [ ! -f "$sp" ]; then 
	echo "Đang tải SpeedTest"; curl -sLo $sp https://bom.to/sparm ; chmod +x $sp; fi; fi

if [ $OS == $Android ]; then sp="/system/xbin/sp"; echo "OS: $OS"; 
	if [ ! -f "$sp" ]; then echo "Đang tải SpeedTest"; curl -sLo $sp https://bom.to/sp64a ; chmod +x $sp; fi; fi

echo "Kiểm tra tốc độ mạng tới máy chủ Việt Nam"
sp -B -s 6106